furman:
  rest:
    base-path: api

  pay:
    mongoDbHost: 127.0.0.1
    mongoDbName: furman-pay
    path: pay

  core:
    datasource:
      url: jdbc:mysql://localhost/public
      username: root
      password: whatsup
      driver-class-name: com.mysql.jdbc.Driver
    path: core

hibernate:
  ejb:
    naming_strategy: org.hibernate.cfg.ImprovedNamingStrategy

#logging:
#  file: mongodb.log
#  level:
#    org.springframework.data.mongodb.repository: 'DEBUG'
