mongoDbHost: 127.0.0.1
mongoDbName: furman

spring:
  packagesToScan:
    furman.domain
  datasource:
    url: jdbc:mysql://localhost/w2test_college
    username: root
    password: whatsup
    driver-class-name: com.mysql.jdbc.Driver

hibernate:
  ejb:
    naming_strategy: org.hibernate.cfg.ImprovedNamingStrategy
