mongoDbHost: 127.0.0.1
mongoDbName: furman

core:
  datasource:
    url: jdbc:mysql://localhost/public
    username: root
    password: whatsup
    driver-class-name: com.mysql.jdbc.Driver

hibernate:
  ejb:
    naming_strategy: org.hibernate.cfg.ImprovedNamingStrategy
